# ====================================================================================================================================
# @file       navsat_transform.yaml
# @author     Tom Moore (ayrton04@gmail.com)
# @author     Steve Macenski (stevenmacenski@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Tuesday, 29th March 2022 5:09:49 pm
# @modified   Wednesday, 13th April 2022 3:29:11 am
# @project    engineering-thesis
# @brief
#    
#    Example configuration for the dual-filter setup node
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# ================================================================================================================================== #
# ------------------------------------------------------- EKF-map filter node ------------------------------------------------------ #
# ================================================================================================================================== #

# EKF filter node
ekf_filter_node_odom:

    # ROS parameters
    ros__parameters:

        # =================================================== General parameters =================================================== #
        
        # Filtering frequency
        frequency: 30.0
        # Sensorical data timeout
        sensor_timeout: 0.1
        # Motion model (2D/3D)
        two_d_mode: false
        # Additional time offset for provided output transform
        transform_time_offset: 0.0
        # TF Transform waiting timeout
        transform_timeout: 0.0
        # Diagnostics
        print_diagnostics: true
        # Debug mode
        debug: false

        # ========================================================= Frames ========================================================= #
        
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        # ================================================== First odometry input ================================================== #
        
        # Topic name
        odom0: odometry/wheel
        # State variables measured
        odom0_config: [false, false, false,
                       false, false, false,
                       true,  true,  true,
                       false, false, true,
                       false, false, false]
        # Advanced configuration
        odom0_queue_size: 10
        odom0_nodelay: true
        odom0_differential: false
        odom0_relative: false

        # ===================================================== First IMU input ==================================================== #
        
        # Topic name
        imu0: imu/data
        # State variables measured
        imu0_config: [false, false, false,
                      true,  true,  false,
                      false, false, false,
                      true,  true,  true,
                      true,  true,  true]
        # Advanced configuration
        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: false
        imu0_queue_size: 10
        imu0_remove_gravitational_acceleration: true

        # ====================================================== Control input ===================================================== #
        
        # Control input not used
        use_control: false

        # ================================================= Advanced configuration ================================================= #
        
        # Process noise
        process_noise_covariance: [
            1e-3, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 1e-3, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 1e-3, 0.00, 0.00, 0.00, 0.00,  0.00,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.3,  0.00, 0.00, 0.00,  0.00,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.3,  0.00, 0.00,  0.00,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.01, 0.00,  0.00,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.5,   0.00,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.5,   0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00,  0.1,  0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00,  0.00, 0.3,  0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00,  0.00, 0.00, 0.3,  0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00,  0.00, 0.00, 0.00, 0.3,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00,  0.00, 0.00, 0.00, 0.00, 0.3,  0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00,  0.00, 0.00, 0.00, 0.00, 0.00, 0.3,  0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.3]

        # Estimation noise (init)
        initial_estimate_covariance: [
            1e-9, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 1e-9, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 1e-9, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 1e-9, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0
        ]


# ================================================================================================================================== #
# ------------------------------------------------------- EKF-map filter node ------------------------------------------------------ #
# ================================================================================================================================== #

# EKF filter node
ekf_filter_node_map:

    # ROS parameters
    ros__parameters:

        # =================================================== General parameters =================================================== #
        
        # Filtering frequency
        frequency: 30.0
        # Sensorical data timeout
        sensor_timeout: 0.1
        # Motion model (2D/3D)
        two_d_mode: false
        # Additional time offset for provided output transform
        transform_time_offset: 0.0
        # TF Transform waiting timeout
        transform_timeout: 0.0
        # Diagnostics
        print_diagnostics: true
        # Debug mode
        debug: false
        
        # ========================================================= Frames ========================================================= #

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: map

        # ==================================================== First odom input ==================================================== #

        # Topic name
        odom0: odometry/wheel
        # State variables measured
        odom0_config: [false, false, false,
                       false, false, false,
                       true,  true,  true,
                       false, false, true,
                       false, false, false]
        # Advanced configuration
        odom0_queue_size: 10
        odom0_nodelay: true
        odom0_differential: false
        odom0_relative: false

        # ==================================================== Second odom input =================================================== #

        # Topic name
        odom1: odometry/gps
        # State variables measured
        odom1_config: [true,  true,  false,
                       false, false, false,
                       false, false, false,
                       false, false, false,
                       false, false, false]
        # Advanced configuration
        odom1_queue_size: 10
        odom1_nodelay: true
        odom1_differential: false
        odom1_relative: false

        # ===================================================== First IMU input ==================================================== #
        
        # Topic name
        imu0: imu/data
        # State variables measured
        imu0_config: [false, false, false,
                      true,  true,  false,
                      false, false, false,
                      true,  true,  true,
                      true,  true,  true]
        # Advanced configuration
        imu0_nodelay: true
        imu0_differential: false
        imu0_relative: false
        imu0_queue_size: 10
        imu0_remove_gravitational_acceleration: true

        # ====================================================== Control input ===================================================== #
        
        # Control input not used
        use_control: false

        # ================================================= Advanced configuration ================================================= #

        # Process noise
        process_noise_covariance: [
            1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 1e-3, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.3,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.3,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.5,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.5,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.1,  0.00, 0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.3,  0.00, 0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.3,  0.00, 0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.3,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.3,  0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.3,  0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.3
        ]

        # Estimation noise (init)
        initial_estimate_covariance: [
            1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 1e-9, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00, 0.00, 0.00,  0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 1e-9, 0.00, 0.00, 0.00, 0.00,  0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00, 0.00,  0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00, 0.00,  0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,  0.00,  0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.0,   0.00, 0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  1.0,  0.00,  0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00, 1.0,   0.00, 0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00, 0.00,  1.0,  0.00, 0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00, 0.00,  0.00, 1.0,  0.0,
            0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,  0.00, 0.00,  0.00, 0.00, 1.0
        ]

# ================================================================================================================================== #
# ----------------------------------------------------- Navstat transform node ----------------------------------------------------- #
# ================================================================================================================================== #

# EKF filter node
navsat_transform:

    # ROS parameters
    ros__parameters:

        # General parameters
        frequency: 30.0
        delay: 3.0
        zero_altitude: false
        broadcast_utm_transform: true
        publish_filtered_gps: true
        use_odometry_yaw: false
        wait_for_datum: false
        # For lat/long 55.944831, -3.186998
        magnetic_declination_radians: 0.0429351
        # IMU reads 0 facing magnetic north, not east
        yaw_offset: 1.570796327
